### ISSUE TITLE
Hi，我启动server后，页面显示not found，请问是缺少了什么步骤吗

### ISSUE THREAD

**Issue by lukchen** [StudentWan/ashen-blog#1]

**Comment by StudentWan** [comment]
整个项目是前后端分离的，server端的作用是api服务器，不负责render页面。

显示页面请启动client端和admin端。

**Comment by lukchen** [comment]
好的，谢谢

**Comment by lukchen** [comment]
你好，我在启动client后出现这个问题

数据库的端口已经改为我自己的了，相应的数据库也有生成。请问这个问题有可能是什么原因？
​

2018-01-13 9:47 GMT-05:00 ashen <notifications@github.com>:

**Comment by StudentWan** [comment]
@lukchen 
你好，收到这个提醒只是因为我关闭了这个issue，而你订阅了这个issue收到的提醒而已。
如果是有其他的问题，那你的图片或者相应的错误似乎没有发上来

P.s. 发现新的bug请开新的issue，这样做有两个好处：
1. 方便维护者接受你的消息，close掉的issue可能不会接到提醒
2. 方便维护者定位bug，改进你遇到的问题

谢谢！
