### ISSUE TITLE
network error问题

### ISSUE THREAD

**Issue by lukchen** [StudentWan/ashen-blog#2]
你好，我在启动client后出现这个问题
![image](https://user-images.githubusercontent.com/26646767/34969065-f85587a2-fa3a-11e7-8ce8-a4b0f78b6a42.png)
![image](https://user-images.githubusercontent.com/26646767/34969077-03cf309c-fa3b-11e7-86ba-f224e450e544.png)

数据库的端口已经改为我自己的了，相应的数据库也有生成。请问这个问题有可能是什么原因？

**Comment by StudentWan** [comment]
@lukchen 
你应该是没有启动server端吧？
server端作为api服务器，与client端和admin端是共同工作的，只是在不同的端口，client端获取数据需要api服务器的支持

**Comment by lukchen** [comment]
是的。。现在正常了。我看到启动client后有'启动server'的log，因为只看了server的代码，以为启动client是同时启动了server，所以想当然还把server关掉了。谢谢答复

**Comment by StudentWan** [comment]
客气了，应该做的。
